# tracker3-endpoint
# Autogenerated from man page /usr/share/man/man1/tracker3-endpoint.1.gz
complete -c tracker3-endpoint -s b -l dbus-service --description 'Service name to use on the endpoint.'
complete -c tracker3-endpoint -s d -l database-path --description 'The path where the database will be stored.'
complete -c tracker3-endpoint -s o -l ontology --description 'The name of an ontology in $datadir/tracker/ontologies to use on the construc…'
complete -c tracker3-endpoint -s p -l ontology-path --description 'Full path to an ontology to use on the constructed database.'
complete -c tracker3-endpoint -l session --description 'Use the session bus.  This is the default.'
complete -c tracker3-endpoint -l system --description 'Use the system bus.'
complete -c tracker3-endpoint -s l -l list --description 'List all SPARQL endpoints available in DBus.'

