# tracker3-export
# Autogenerated from man page /usr/share/man/man1/tracker3-export.1.gz
complete -c tracker3-export -s g -l show-graphs --description 'Tracker can separate data into multiple graphs.'
complete -c tracker3-export -l 2to3 --description 'Helper for migrating data from Tracker 2. x databases.'
complete -c tracker3-export -l keyfile --description 'Outputs the data in a key file format.  Only may be used with --2to3.'

